name: Build and Test
on: [push]
env:
  build_type: RELEASE
  build_directory: ${{github.workspace}}/build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Change default version to GCC 14
        # GCC 14 is already installed
        # needed for some C23, namely stdckint.h. Can be removed when ubuntu-latest becomes 26.04
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --set gcc /usr/bin/gcc-14
      - uses: actions/checkout@v7
      - run: cmake -B ${{env.build_directory}} -DCMAKE_BUILD_TYPE=${{env.build_type}}
      - run: cmake --build ${{env.build_directory}} --config ${{env.build_type}}
      - run: ctest --test-dir ${{env.build_directory}}
